---
output:
  html_document:
    keep_md: yes
---

SpatialEpi
===========================================
Methods and Data for Spatial Epidemiology
-------------------------------------------
We load the data and convert the coordinate system from latitude/longitude to a 
grid-based system.  
```{r}
library(SpatialEpi)
data(NYleukemia)
sp.obj <- NYleukemia$spatial.polygon
centroids <- latlong2grid(NYleukemia$geo[, 2:3])
population <- NYleukemia$data$population
cases <- NYleukemia$data$cases
```

We plot the incidence of leukemia for each census tract.  
```{r, fig.height=8, fig.width=8, fig.path='./figure/'}
plotmap(cases/population, sp.obj, log=TRUE, nclr=5)
points(grid2latlong(centroids), pch=4)
```

We run the Bayesian Cluster Detection method from Wakefield and Kim (2013)
```{r, fig.height=8, fig.width=8, fig.path='./figure/', cache=TRUE}
y <- cases
E <- expected(population, cases, 1)
max.prop <- 0.15
shape <- c(2976.3, 2.31)
rate <- c(2977.3, 1.31)
J <- 7
pi0 <- 0.95
n.sim.lambda <- 10^4
n.sim.prior <- 10^5
n.sim.post <- 10^5

# Compute output
output <- bayes_cluster(y, E, population, sp.obj, centroids, max.prop, 
 shape, rate, J, pi0, n.sim.lambda, n.sim.prior, n.sim.post)
plotmap(output$post.map$high.area, sp.obj)
```


