# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normalize <- function(x) {
    .Call('_SpatialEpi_normalize', PACKAGE = 'SpatialEpi', x)
}

NumericVectorEquality <- function(x, y) {
    .Call('_SpatialEpi_NumericVectorEquality', PACKAGE = 'SpatialEpi', x, y)
}

ldnbinom <- function(y, E, a, b) {
    .Call('_SpatialEpi_ldnbinom', PACKAGE = 'SpatialEpi', y, E, a, b)
}

ldmultinom <- function(x, prob) {
    .Call('_SpatialEpi_ldmultinom', PACKAGE = 'SpatialEpi', x, prob)
}

coeff <- function(y_vector, E_vector, a_values, b_values, cluster_list) {
    .Call('_SpatialEpi_coeff', PACKAGE = 'SpatialEpi', y_vector, E_vector, a_values, b_values, cluster_list)
}

ProbSampleReplace <- function(prob) {
    .Call('_SpatialEpi_ProbSampleReplace', PACKAGE = 'SpatialEpi', prob)
}

check_overlap <- function(config, overlap) {
    .Call('_SpatialEpi_check_overlap', PACKAGE = 'SpatialEpi', config, overlap)
}

clean_moves_matrix <- function(theta, moves, n_zones) {
    .Call('_SpatialEpi_clean_moves_matrix', PACKAGE = 'SpatialEpi', theta, moves, n_zones)
}

return_death_moves <- function(theta) {
    .Call('_SpatialEpi_return_death_moves', PACKAGE = 'SpatialEpi', theta)
}

return_birth_moves <- function(theta, overlap) {
    .Call('_SpatialEpi_return_birth_moves', PACKAGE = 'SpatialEpi', theta, overlap)
}

return_local_moves <- function(theta, overlap, cluster_coords) {
    .Call('_SpatialEpi_return_local_moves', PACKAGE = 'SpatialEpi', theta, overlap, cluster_coords)
}

MCMC_simulation <- function(n_sim, pattern, theta_init, overlap, cluster_coords, p_moves_orig, J, lkhd_z, lambda) {
    .Call('_SpatialEpi_MCMC_simulation', PACKAGE = 'SpatialEpi', n_sim, pattern, theta_init, overlap, cluster_coords, p_moves_orig, J, lkhd_z, lambda)
}

binomialLogLkhd <- function(cz, nz, N, C) {
    .Call('_SpatialEpi_binomialLogLkhd', PACKAGE = 'SpatialEpi', cz, nz, N, C)
}

poissonLogLkhd <- function(cz, nz, N, C) {
    .Call('_SpatialEpi_poissonLogLkhd', PACKAGE = 'SpatialEpi', cz, nz, N, C)
}

computeAllLogLkhd <- function(observedCases, expectedCases, nearestNeighborsList, nZones, logLkhdType) {
    .Call('_SpatialEpi_computeAllLogLkhd', PACKAGE = 'SpatialEpi', observedCases, expectedCases, nearestNeighborsList, nZones, logLkhdType)
}

kulldorffMC <- function(permutedCaseMatrix, expectedCases, nearestNeighbors, nZones, logLkhdType) {
    .Call('_SpatialEpi_kulldorffMC', PACKAGE = 'SpatialEpi', permutedCaseMatrix, expectedCases, nearestNeighbors, nZones, logLkhdType)
}

besag_newell_internal <- function(observedCases, expectedCases, nearestNeighborsList, nZones, k) {
    .Call('_SpatialEpi_besag_newell_internal', PACKAGE = 'SpatialEpi', observedCases, expectedCases, nearestNeighborsList, nZones, k)
}

