# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normalize <- function(x) {
    .Call(`_SpatialEpi_normalize`, x)
}

NumericVectorEquality <- function(x, y) {
    .Call(`_SpatialEpi_NumericVectorEquality`, x, y)
}

ldnbinom <- function(y, E, a, b) {
    .Call(`_SpatialEpi_ldnbinom`, y, E, a, b)
}

ldmultinom <- function(x, prob) {
    .Call(`_SpatialEpi_ldmultinom`, x, prob)
}

coeff <- function(y_vector, E_vector, a_values, b_values, cluster_list) {
    .Call(`_SpatialEpi_coeff`, y_vector, E_vector, a_values, b_values, cluster_list)
}

ProbSampleReplace <- function(prob) {
    .Call(`_SpatialEpi_ProbSampleReplace`, prob)
}

check_overlap <- function(config, overlap) {
    .Call(`_SpatialEpi_check_overlap`, config, overlap)
}

clean_moves_matrix <- function(theta, moves, n_zones) {
    .Call(`_SpatialEpi_clean_moves_matrix`, theta, moves, n_zones)
}

return_death_moves <- function(theta) {
    .Call(`_SpatialEpi_return_death_moves`, theta)
}

return_birth_moves <- function(theta, overlap) {
    .Call(`_SpatialEpi_return_birth_moves`, theta, overlap)
}

return_local_moves <- function(theta, overlap, cluster_coords) {
    .Call(`_SpatialEpi_return_local_moves`, theta, overlap, cluster_coords)
}

MCMC_simulation <- function(n_sim, pattern, theta_init, overlap, cluster_coords, p_moves_orig, J, lkhd_z, lambda) {
    .Call(`_SpatialEpi_MCMC_simulation`, n_sim, pattern, theta_init, overlap, cluster_coords, p_moves_orig, J, lkhd_z, lambda)
}

binomialLogLkhd <- function(cz, nz, N, C) {
    .Call(`_SpatialEpi_binomialLogLkhd`, cz, nz, N, C)
}

poissonLogLkhd <- function(cz, nz, N, C) {
    .Call(`_SpatialEpi_poissonLogLkhd`, cz, nz, N, C)
}

computeAllLogLkhd <- function(observedCases, expectedCases, nearestNeighborsList, nZones, logLkhdType) {
    .Call(`_SpatialEpi_computeAllLogLkhd`, observedCases, expectedCases, nearestNeighborsList, nZones, logLkhdType)
}

kulldorffMC <- function(permutedCaseMatrix, expectedCases, nearestNeighbors, nZones, logLkhdType) {
    .Call(`_SpatialEpi_kulldorffMC`, permutedCaseMatrix, expectedCases, nearestNeighbors, nZones, logLkhdType)
}

besag_newell_internal <- function(observedCases, expectedCases, nearestNeighborsList, nZones, k) {
    .Call(`_SpatialEpi_besag_newell_internal`, observedCases, expectedCases, nearestNeighborsList, nZones, k)
}

