# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute binomial likelihood ratio test statistic for Kulldorff method.
#' 
#' @param cz Disease count inside single zone.
#' @param nz Expected count inside single zone.
#' @param C Total disease count in region.
#' @param N Total expected count in region.
#' @return log of likelihood ratio test statistic.
#' @export
binomialLogLkhd <- function(cz, nz, C, N) {
    .Call('SpatialEpi_binomialLogLkhd', PACKAGE = 'SpatialEpi', cz, nz, C, N)
}

#' Compute poisson likelihood ratio test statistic for Kulldorff method.
#' 
#' @inheritParams binomialLogLkhd
#' @return log of likelihood ratio test statistic.
#' @export
poissonLogLkhd <- function(cz, nz, C, N) {
    .Call('SpatialEpi_poissonLogLkhd', PACKAGE = 'SpatialEpi', cz, nz, C, N)
}

#' Compute log likelihood ratio test statistic for all single zones.
#' 
#' @param observedCases
#' @param expectedCases
#' @param nearestNeighborsList
#' @param nZones
#' @param logLkhdType
#' @return Vector of log likelihood
#' @export
computeAllLogLkhd <- function(observedCases, expectedCases, nearestNeighborsList, logLkhdType) {
    .Call('SpatialEpi_computeAllLogLkhd', PACKAGE = 'SpatialEpi', observedCases, expectedCases, nearestNeighborsList, logLkhdType)
}

#' Compute log likelihood ratio test statistic for all 
#' 
#' @inheritParams computeAllLogLkhd
#' @param permutedCaseMatrix blah
#' @return Max
#' @export
kulldorffMC <- function(permutedCaseMatrix, expectedCases, nearestNeighborsList, logLkhdType) {
    .Call('SpatialEpi_kulldorffMC', PACKAGE = 'SpatialEpi', permutedCaseMatrix, expectedCases, nearestNeighborsList, logLkhdType)
}

multinom <- function(size, probs) {
    .Call('SpatialEpi_multinom', PACKAGE = 'SpatialEpi', size, probs)
}

kulldorffMC2 <- function(nSims, expectedCases, nearestNeighborsList, logLkhdType) {
    .Call('SpatialEpi_kulldorffMC2', PACKAGE = 'SpatialEpi', nSims, expectedCases, nearestNeighborsList, logLkhdType)
}

